"""Curated, hand-maintained verification status per logical tool name.

`lmutil lmstat` has already been proven unreliable as a predictor of real tool
usability on this machine — PowerSI and PowerDC both fetch licenses and run
successfully, repeatedly, despite `lmstat` reporting the configured license server
unreachable. Building an automated "ping the license server per tool" status feature on
top of that already-unreliable signal would mislead callers, not help them. Worse, an
automated *launch-and-see* probe is actively risky for GUI-capable tools: a single
`allegro.exe -product help` probe (documented as print-and-exit) instead blocked
indefinitely on an interactive product-chooser dialog.

So instead of a live query, this module is a single source of truth for what has
actually been exercised, updated by hand as tools are tested — the same three-tier
distinction this project's README already draws in prose, made queryable here instead.
"""

from __future__ import annotations

from typing import Literal

ToolStatus = Literal["confirmed_live", "built_untested", "known_blocked"]

STATUS_DESCRIPTIONS: dict[ToolStatus, str] = {
    "confirmed_live": "Actually run against a real license and a real design on this "
    "machine, successfully, at least once.",
    "built_untested": "Implemented from documentation/sample scripts and covered by "
    "unit tests (argv/script construction), but never executed against a live license "
    "on this machine — treat exact flag/command spellings as best transcription, not "
    "guaranteed correct.",
    "known_blocked": "Attempted live and found genuinely blocked (a license issue, an "
    "unresolved interactive prompt, or similar) — see the note for specifics before "
    "retrying.",
}

# logical tool name (matches core.executables' registries) -> status.
# Anything not listed here is implicitly "built_untested" if registered in the
# executables registry at all, or simply unknown to this suite otherwise.
TOOL_STATUS: dict[str, ToolStatus] = {
    "powersi": "confirmed_live",
    "powerdc": "confirmed_live",
    "amlibgen": "known_blocked",
    "allegro": "confirmed_live",
    "capture": "known_blocked",
    "allegro_batch": "known_blocked",
    "allegro_report": "confirmed_live",
    "allegro_dbdoctor": "confirmed_live",
    "celsius3d": "confirmed_live",
    "celsiuscfd": "confirmed_live",
    "celsius2d": "confirmed_live",
    "allegro_batch_drc": "confirmed_live",
    "allegro_placement": "confirmed_live",
    "allegro_ncroute": "confirmed_live",
    "allegro_ipc2581_out": "confirmed_live",
    "allegro_ipc356_out": "confirmed_live",
    "allegro_step_out": "confirmed_live",
    "ibischk3": "built_untested",
    "ibischk4": "built_untested",
    "ibischk5": "built_untested",
    "ibischk6": "confirmed_live",
    "allegro_checkplus": "known_blocked",
    "allegro_artwork": "confirmed_live",
    "allegro_gbplot": "built_untested",
    "allegro_designextractor": "known_blocked",
    "allegro_extracta": "confirmed_live",
    "allegro_zrouter": "built_untested",
    "allegro_diacheck": "built_untested",
    "allegro_diacompare": "built_untested",
    "con2xml": "known_blocked",
    "cap2xml": "known_blocked",
    "dml2con": "known_blocked",
    "apd2con": "known_blocked",
    "abcd": "known_blocked",
    "bem2d3": "built_untested",
    "xcitepi": "confirmed_live",
    "optimizepi": "confirmed_live",
    "xtractim": "confirmed_live",
    "dsn2spd": "confirmed_live",
    "spdsim": "known_blocked",
    "t2b": "known_blocked",
    "spif_batch": "confirmed_live",
    "specctra": "confirmed_live",
    "psp_cmd": "confirmed_live",
    "dxf2a": "confirmed_live",
    "a2dxf": "confirmed_live",
    "ipc2581_in": "confirmed_live",
    "idf_out": "confirmed_live",
    "idx_out": "confirmed_live",
    "idf_in": "built_untested",
    "idx_in": "built_untested",
    "brd2dml": "confirmed_live",
    "pdf_out": "confirmed_live",
    "copyproject": "confirmed_live",
    "xcon2project": "confirmed_live",
    "generate_sim_variant": "confirmed_live",
    "create_sym": "confirmed_live",
}
# NOTE: allegro_constraint_tools.py's and allegro_geometry_tools.py's individual SKILL
# calls all execute through the single "allegro" logical tool above (same session/
# process mechanics) — their own per-call reliability is finer-grained than this
# executable-keyed dict models, so it's documented in the "allegro" note below instead
# of as separate top-level entries here.

# Free-text detail for any status worth explaining beyond STATUS_DESCRIPTIONS' generic
# wording — mainly for known_blocked entries, so a caller knows what to actually do.
TOOL_STATUS_NOTES: dict[str, str] = {
    "amlibgen": "Root cause confirmed and it is NOT a license issue: "
    "AmLibGen.exe writes its own log file (`AMLibGen.log`, in its process's launch "
    "directory, not the job's own directory — this tool goes through core.process."
    "run_quick, not submit_job, so it inherits this server's own cwd rather than a "
    "per-job scratch dir) showing it receives the exact command line correctly, begins "
    "processing the source spreadsheet, then fails with '[ERROR] Init excel failed' — "
    "consistent with a broken/missing Microsoft Excel COM automation dependency on this "
    "machine for reading legacy .xls files, not a FlexNet/license problem and not a CLI "
    "flag error (the flags in generate_amm_library_from_spreadsheet are confirmed "
    "correct — the tool parsed and acted on them). Needs Excel installed/repaired on "
    "this machine (or a native .xlsx source, if AmLibGen supports one, to bypass "
    "whatever legacy .xls COM path is failing) to fully confirm end-to-end — flag this "
    "for the user, it is not something a license grant fixes.",
    "allegro": "An interactive 'Product Choices' license-tier chooser dialog blocks "
    "every launch until a default product is set once via the GUI (confirmed not a "
    "license failure -- Sigrity Aurora and other tiers are genuinely listed as "
    "available choices). With a default product set, confirmed live for the "
    "session/query mechanics: `allegro.exe -s script.scr <real .brd>` loads the board "
    "and a `skill (axlCurrentDesign)` query executed and returned correctly, followed by "
    "a clean `quit`-triggered exit, all within ~20s. `allegro_create_net` "
    "(`axlDBCreateNet`) against a real board completes cleanly in ~5.6s (returncode 0); "
    "a hang past two minutes in the same session shape is license/queue-related, not a "
    "bug in the SKILL call itself. Only `allegro_create_net` "
    "was independently confirmed this way; `allegro_create_component`/"
    "`allegro_create_board_outline`/`allegro_create_stackup`/`allegro_save_design`/"
    "`allegro_run_drc` use the same session mechanics and the same axl* API family but "
    "were not each individually run -- reasonable to expect they also work, but "
    "still technically unverified individually. For "
    "allegro_constraint_tools.py/allegro_geometry_tools.py (tested both directly and "
    "via two independent LLM-driven runs, both configured endpoints): "
    "`allegro_set_spacing_constraint`/`allegro_set_physical_constraint` "
    "(axlCNSSetSpacing/axlCNSSetPhysical) and `allegro_create_via` (axlDBCreateVia) all "
    "ran cleanly to completion (returncode 0, no hang) in every one of 3 independent "
    "live runs (1 direct + 2 LLM-driven) when combined with axlSaveDesign in the same "
    "session -- promoted to confirmed_live for the session-mechanics/no-hang claim "
    "(whether the constraint/via values landed exactly as specified was not separately "
    "verified by reading the modified board back, only that the session ran and exited "
    "cleanly). `allegro_assign_net` (axlDBAssignNet via a `(car (axlSelectByName ...))` "
    "resolver) was previously misreported here as known_blocked, based on a test "
    "where the session ran for several minutes with no save landing on disk -- that "
    "long-running symptom turned out to be a self-inflicted artifact of firing off "
    "several overlapping diagnostic sessions at once, competing for a limited license "
    "seat, not a bug in the SKILL call itself (the same class of false negative as the "
    "original axlDBCreateNet block). Run cleanly one Allegro launch at a time: three "
    "independent live confirmations against fresh "
    "copies of the real sample board -- (1) a hand-written SKILL macro resolving "
    "R1.2/GND via axlSelectByName and calling axlDBAssignNet directly, (2) the exact "
    "production allegro_assign_net/allegro_save_design/allegro_run_session tool "
    "functions unmodified, and (3) independently re-reading the saved board with "
    "report.exe (bypassing SKILL entirely) both before (pristine board: "
    "'N00885,R1.2 R4.1 U1.1 U3.3') and after ('GND,...R1.2...' / 'N00885,R4.1 U1.1 U3.3' "
    "-- R1.2 genuinely moved nets on disk). PROMOTED to confirmed_live -- net "
    "reassignment via this tool is real and does persist. Also tested: Allegro's native "
    "`auto_route` Command:-prompt command "
    "(not SKILL -- the officially documented single-command SPECCTRA round-trip driver, "
    "`doc/algroroute/chap12.html`) as a possible fix for spif_batch -i's crash -- it "
    "also failed, with a crash-style negative return code, so this is not a working "
    "alternative either. A separate, distinct intermittent failure mode exists, "
    "surfaced via the vLLM-driven manufacturing eval (scripts/eval_manufacturing.py): "
    "`allegro_run_session` can return `state=failed, returncode=-536870904` after almost "
    "exactly ~137-138s, with run.log showing only the startup banner -- the same "
    "specific negative code and ~137s duration recurs across multiple diagnostic runs, "
    "independent of the stale-lock root cause above (already found and fixed). This "
    "occurs even with NO overlapping Allegro launches "
    "(strictly sequential harness, board freshly copied) and no pre-existing lock file, "
    "so it is a genuinely separate, still-not-fully-isolated cause -- possibly a "
    "different modal dialog, a transient license-server hiccup, or something else "
    "entirely; the consistent ~137s timing across every occurrence suggests a real "
    "internal watchdog/timeout rather than a random crash. Calling the new "
    "`check_design_lock` diagnostic tool afterward reliably finds a "
    "lock the failed run itself orphaned, after which the rest of "
    "the pipeline can continue normally. Treat an Allegro batch launch that's still `running` well past its "
    "usual 15-20s load time, or that fails with this exact code, as a known, real, "
    "empirically-recurring (roughly 1-in-4 launches) reliability "
    "issue -- not yet fully root-caused, retry rather than treat as a hard blocker. "
    "STACKUP AUTHORING: `allegro_create_stackup` (allegro_tools.py) was "
    "upgraded from a bare `(axlXSectionCreate nil 'position)` no-op-ish call (only ever "
    "created one unnamed default-material dielectric) to build a real "
    "`make_axlXSection(?name ?layerType ?material ?thickness)` defstruct, and a new bulk "
    "tool `generate_multilayer_stackup` (rigid_flex_stackup_tools.py) composes N of these "
    "in one session for a full stackup. Confirmed live for this specific "
    "capability: run live 4 times against fresh copies of the real sample board -- a "
    "3-layer test (twice, once with an ordering bug then again after fixing it) and the "
    "full real 18-layer `build_18layer_rigid_flex_stackup_definition()` list -- each time "
    "independently verified (bypassing SKILL entirely) by re-reading the saved board with "
    "`run_allegro_report(..., report_code=\"x-section\")`. CONFIRMED: name/layerType/"
    "material/thickness are genuinely authored and land in the correct top-to-bottom "
    "order PROVIDED you queue layers via `axlXSectionCreate(nil 'bottom <defstruct>)` IN "
    "THE SAME order as your top-to-bottom layer list (NOT reversed -- a literal reading of "
    "axlXSectionCreate.txt's own \"build the stackup from bottom to top\" tip was tried "
    "first and empirically produced the OPPOSITE, inverted order; see "
    "generate_multilayer_stackup's docstring for the full before/after evidence). FOUND: "
    "creating a layer whose `name` collides with the board's existing default TOP/BOTTOM "
    "outer layer (as the 18-layer definition's own layer 1/18 do, both literally named "
    "\"TOP\"/\"BOTTOM\") is a silent no-op -- no duplicate, no error, no change to the "
    "existing entry's attributes; only the 16 internal layers of that 18-layer list "
    "actually get created, matching Cadence's documented \"does not allow name layers "
    "above top or below bottom\" restriction. FOUND (separately from the ~1-in-4 general "
    "flakiness above): every one of these 4 stackup-authoring runs raised a modal Qt "
    "dialog a couple seconds into the run, requiring "
    "`core.win32gui_helper.auto_dismiss_dialogs(pid)` running concurrently to avoid an "
    "indefinite hang -- appeared content-independent (also hit a bare 2-layer isolation "
    "test) so likely the same launch flakiness, but reproduced 4-for-4 across these runs versus "
    "the historical ~1-in-4, so treat it as a near-certainty for this workflow specifically "
    "until disproven. NOT settable via any SKILL API found on this install (searched the "
    "full axlXSectionGet.txt attribute table plus every axlCNS*/axlCns* Constraint-Manager "
    "function): an explicit electrical \"reference plane\" assignment -- Allegro infers this "
    "from stackup adjacency to a PLANE layer, not a field you set, so `ref_plane`/`zone`/"
    "`hatched_plane` in a layer dict are metadata-only, not real SKILL calls. "
    "ROOT-CAUSED AND FIXED a real, reproducible (3-for-3) indefinite hang in "
    "`run_allegro_specctra_import` (spif_specctra_tools.py) that previously blocked a "
    "SPECCTRA-route-then-import flow -- NOT the same bug as `spif_batch -i`'s SPMHDB-238 crash "
    "(that one dies immediately with a readable error; this one hangs forever, 0% CPU, 0 new "
    "windows, run.log stuck at the 3-line startup banner forever). Root cause: the script-replay "
    "line the tool emitted was literally `specctra in "
    "\"<path>\"` (two words, a space) -- not a real Allegro command. The real, documented command "
    "is `specctra_in` (one word, underscore; confirmed against `doc/scoms/schap.html`'s own command "
    "reference, which names it consistently throughout). Typing the wrong two-word form puts "
    "Allegro's command dispatcher into a permanently stuck state with no dialog and no further "
    "output -- confirmed live via an isolated repro (scratch board/session copies under "
    "`runs/specctra_import_investigation/`): the exact same hang "
    "shape reproduced identically, then switching only `in ` -> `_in` in the emitted script line "
    "made the process exit cleanly in under 2 seconds instead of hanging. A SECOND, independent bug "
    "was found while verifying the first fix: `specctra_in <file>` (CONFIRMED live, via the replay "
    "journal, to accept the session path as a same-line argument and auto-click Run -- not just the "
    "bare dialog-opener the docs describe) leaves its dialog (`share/pcb/text/forms/spif_in.form`, "
    "form name `spif_in`, fields `SES_IN`/`TRANSLATE_TO`/`CLOSE`) open afterward; any following "
    "top-level command (the save, even `quit`) was refused with a real, logged `Finish current "
    "command first` error and silently did nothing -- so the import itself worked but nothing after "
    "it did. Fixed by inserting `setwindow form.spif_in` / `FORM spif_in CLOSE` / `setwindow pcb` "
    "between the `specctra_in` line and whatever runs next. A THIRD, unrelated pre-existing bug was "
    "also found and fixed in the same function (and, identically, in `allegro_placement_tools.py`'s "
    "zrouter save and `aurora/scope_tools.py`'s workflow save -- same copy-pasted line in all three): "
    "`(axlSaveDesign ?noCheck t)` used a keyword, `?noCheck`, that does not exist in `axlSaveDesign`'s "
    "real signature (confirmed against the vendored `axlSaveDesign.txt` SKILL doc: the real no-db-"
    "check option is `?mode \"nocheck\"`, a string option, not a boolean keyword) -- every save after "
    "these three operations was silently failing (`*Error* axlSaveDesign: unrecognized keyword - "
    "?noCheck`, logged only to Allegro's own `.jrl` journal, never to the job's `run.log`/return code) "
    "while the job still reported `succeeded`. All three fixes were LIVE-VERIFIED together end to "
    "end through the actual (patched) `run_allegro_specctra_import` function, not just read for "
    "correctness: a real routed `.ses` (100% connected, 75 nets/163 connections, reused from this "
    "suite's own earlier confirmed-live autoroute) was imported into a fresh board copy, the import "
    "job reported `succeeded`, a real output `.brd` was written (913896 bytes vs the 760024-byte "
    "source -- genuinely different, sha1 differs), and `report.exe` (an independent, SKILL-free "
    "verification path, already `confirmed_live` elsewhere in this file) read the saved board back "
    "and reported real routed-geometry statistics matching the source exactly: Connection "
    "Completion 100.00%, 163/163 connections, 451.50 inches of total trace length, 0 vias. "
    "`run_allegro_specctra_import` is correspondingly promoted from \"recommended but unverified\" to "
    "CONFIRMED LIVE end-to-end -- the real, working way to get routed SPECCTRA geometry back into an "
    "Allegro board on this install, now that `spif_batch -i`'s crash no longer needs a workaround "
    "that itself didn't work. "
    "COPPER SHAPE / PLANE POUR: `generate_multilayer_stackup` authors layer STRUCTURE "
    "(name/layerType/material/thickness via axlXSectionCreate) but never created any actual copper -- "
    "a new tool, `allegro_create_copper_shape` (axlDBCreateShape, allegro_geometry_tools.py), closes "
    "this gap. CONFIRMED LIVE, 3 independent ways, against a fresh real board copy with a real 8-layer "
    "stackup (6 new layers incl. 2 PLANE layers, via generate_multilayer_stackup): (1) an in-session "
    "SKILL query (`axlDBGetShapes(\"BOUNDARY/L2_GND\")`) immediately after creation, captured to a file "
    "via SKILL's own outfile/fprintf, returned a real non-nil shape dbid; (2) a SECOND, completely "
    "independent Allegro process (fresh `allegro.exe` launch, no shared memory with the session that "
    "created it) opening the already-saved board from disk found the SAME shape on BOTH "
    "`BOUNDARY/L2_GND` (the dynamic pour definition) and `ETCH/L2_GND` (1 shape each) -- confirming the "
    "dynamic/BOUNDARY shape genuinely generates real computed ETCH copper, matching "
    "axlShapeChangeDynamicType.txt's own description of BOUNDARY-class dynamic shapes generating real "
    "ETCH-layer copper; (3) translating the board to `.spd` via the already-confirmed-live PowerSI BRD-"
    "bridge (start_powersi_session + powersi_save_document) produced a `.spd` containing a real "
    "`.Shape Plane$L2_GNDpkgshape` / `PatchSignal$L2_GND Shape = Plane$L2_GNDpkgshape Layer = "
    "Signal$L2_GND` block with real `Node<n>::GND ... Layer = Signal$L2_GND` entries -- an entirely "
    "separate translation engine (SPDIF) independently confirming the pour is real geometry, not a "
    "SKILL-session artifact. KEY FINDING (corrects an original design assumption): auto-deriving the "
    "pour boundary from `axlDBGetShapes(\"BOARD GEOMETRY/OUTLINE\")` (\"pour the whole board outline "
    "with no coordinates needed\") was tried first and LIVE-DISPROVEN -- on the real Fault-Detector "
    "sample board this returned nil; the board's physical outline is drawn as plain LINE/ARC segments, "
    "not a shape database object (confirmed: the board has 157 real shapes total, all of them "
    "`PACKAGE GEOMETRY/*` component silkscreen/assembly/place-bound outlines -- zero `BOARD GEOMETRY/*` "
    "shapes of any kind). A components-bounding-box fallback (`axlDBGetExtents(axlDBGetDesign()->"
    "components nil)`) was also tried live and returned a degenerate `((0.0 0.0) (0.0 0.0))` box, so "
    "`allegro_create_copper_shape` instead REQUIRES an explicit `points` boundary (no silent, possibly-"
    "empty default) -- see the tool's own docstring for the full live evidence. HYPOTHESIS TESTED AND "
    "NOT CONFIRMED: the suspected downstream payoff -- that this fix would unblock PowerDC `sigrity::add "
    "pdcVRM -auto -net {power,ground} ...` binds that previously failed with \"The net pair ... is not "
    "specified\" -- did NOT materialize. See the new `powerdc` note below for the full, separate "
    "investigation: the exact same error reproduces identically whether or not real copper exists on "
    "the plane layer, across 4 independent variations, so the VRM failure has a different root cause "
    "entirely, unrelated to this fix. "
    "ROUTING-QUALITY-ANALYSIS AND MANUAL-OVERRIDE INVESTIGATION: tested, live, whether this "
    "suite can (a) analyze routing quality/performance beyond pass-fail DRC, and (b) surgically rip up "
    "and refix one specific bad route without redoing the whole board. Used the real routed Fault-"
    "Detector sample (`scenario_6/fd.brd`, 81 components/75 nets/163 connections, 2 pre-existing DRC "
    "errors incl. 1 real short) copied into a private `runs/routing_capability_investigation/` scratch "
    "dir. FOUND TWO REAL GAPS AND CLOSED THEM: (1) no tool queried a net's real measured routed length "
    "(only `allegro_get_net_constraint`/`axlCnsNetFlattened` existed, which returns a RULE value like "
    "MAX_VIAS, never a measured length) -- added `allegro_get_net_length` (`axlDBGetLength`, "
    "allegro_geometry_tools.py), confirmed live returning real values (e.g. net X8=2447.5 mil, "
    "N03774=5177.5 mil, captured via the same outfile/fprintf technique this module already documents "
    "for other SKILL return values). (2) no delete/rip-up tool existed at all -- added "
    "`allegro_delete_connect` (`axlDeleteObject`, same file), confirmed live, but with an important "
    "CAVEAT discovered the hard way: `axlDeleteObject` on a NET-type dbid (even with `'ripup`) deletes "
    "the net's LOGICAL IDENTITY ENTIRELY, not just its etch -- live-reproduced: after calling it on net "
    "X8, `run_allegro_report(..., report_code=\"net\")` showed X8 had vanished from the net list "
    "completely (nets 75->74), its 2 pins went from W/Rats to Unused, and a subsequent "
    "`allegro_create_trace(..., net_name=\"X8\")` created NOTHING (axlDBCreatePath silently returns nil "
    "for a nonexistent net net_name, per its own vendored doc) -- so this is NOT a safe rip-up-for-"
    "reroute mechanism for whole nets. The REAL, already-existing, non-destructive mechanism for that is "
    "`allegro_assign_net(object_type=\"PIN\", ..., net_name=<the pin's own current net>, ripup=True)` -- "
    "live-confirmed via `axlDBGetConnect`/net attribute queries that this correctly strips the connected "
    "clines (net goes to `unconnected=1`/ratsnest) while leaving the net and both pins fully intact, "
    "ready for a clean re-route. `allegro_delete_connect` remains useful for its documented purpose "
    "(genuinely deleting an object -- a stray component, an obsolete film, etc.), just not for this "
    "specific workflow; SKILL.md and the tool's own docstring now say so explicitly. "
    "TWO ADDITIONAL REAL, PREVIOUSLY-UNDISCOVERED BUGS were found and FIXED in the existing "
    "(`confirmed_live`) `allegro_create_trace` tool while exercising this live rip-up-and-refix cycle: "
    "(a) it passed the caller's bare layer name (e.g. `\"TOP\"`) straight to `axlDBCreatePath`'s t_layer "
    "argument; the vendored `axlDBCreatePath.txt` doc's own worked example uses the full class/subclass "
    "string (`\"ETCH/TOP\"`) -- live-reproduced the bare form silently creating NOTHING (nil return, 0 "
    "segments, `Missing Connections: 1` on an otherwise-clean board) even though the job still exited rc "
    "0; fixed by building `\"ETCH/<layer>\"` automatically (same convention `allegro_create_copper_shape` "
    "already used correctly for shapes). (b) it called `axlPathStart(points)` with NO width argument; "
    "per `axlPathStart.txt`, the second argument IS the trace width and silently defaults to 0 if "
    "omitted -- live-reproduced via `axlDBGetConnect`'s own segment/width attributes showing `width=0.0` "
    "on every segment of a tool-created trace, which in turn produced real new \"Minimum Neck Width\" "
    "DRC violations (required 5 MIL, actual 0 MIL) and spurious near-0-clearance spacing violations "
    "against unrelated nearby copper; fixed by adding a REQUIRED `width` parameter (no silent default) "
    "threaded into `axlPathStart`. Both fixes independently re-verified live (before/after `Missing "
    "Connections`/DRC-violation-type comparison) and covered by new/updated unit tests. END-TO-END RESULT "
    "on the real board: using the corrected tools, the originally-targeted DRC violation (a real 0 MIL "
    "\"Line to Line Spacing\" short between net X8 and net N03774 at the exact marker coordinate "
    "`(11762.5, 17005.0)`, independently located via a live `axlDBGetConnect` segment-geometry query that "
    "matched the DRC report's own marker location to the mil) was DEFINITIVELY, REPEATEDLY fixed -- every "
    "corrected attempt showed `Short DRC` go from 1 to 0, `DRC Errors` drop by exactly 1 (only the "
    "pre-existing, unrelated Package-to-Package placement violation remained), `Missing Connections: 0`, "
    "`Connection Completion: 100.00%`, and exact, unchanged Nets(75)/Pins(251) counts -- full fidelity of "
    "the rest of the board, confirmed via `run_allegro_batch_drc` + independent `run_allegro_report` "
    "re-reads (bypassing SKILL), not just trusting job state. HONEST LIMITATION FOUND: net X8 turned out "
    "to be one lane of a tightly-packed 8-line parallel mux bus (X1-X8, pin-adjacent on U5/U8) running "
    "directly through a separately-dense analog feedback-network pocket (nets N03774/N03806/N02125/"
    "N01060/C4's N21503/N21197, each weaving through the same ~600x1200 mil area) -- picking a fully "
    "clean ALTERNATE reroute geometry by hand required discovering each of these neighbors one at a time "
    "via live `axlDBGetConnect` queries (this project's own equivalent of \"read the keepout map before "
    "routing\"), and even a carefully-reasoned, maximally-surgical reroute (reusing 3 of the original "
    "4 safe segments, deviating by as little as geometrically possible) still left double-digit new "
    "spacing violations against previously-unseen neighbors in this specific pocket. This is a genuine, "
    "board-density-dependent limitation of MANUAL point-coordinate rerouting (same as a human hand-"
    "routing this exact spot would face) -- not a gap in the tool chain itself, which performed exactly "
    "as asked at every step (rip-up, create, save, run, verify were all fast -- each DRC+report re-check "
    "cycle took under 2 seconds -- making the iterate-and-recheck workflow itself genuinely practical). "
    "SCALED TO A HARDER, LENGTH-MATCHING CASE: real per-net lengths were queried live for 4 structurally-"
    "analogous \"matched leg\" nets of a repeating LED-driver sub-circuit (N08416=13062.5, "
    "N08752=10567.51, N08984=8052.5, N09192=12677.5 mil -- a huge, real, unmatched spread), compared "
    "against a real `get_high_speed_constraint_preset(\"DDR4\")` tolerance "
    "(`addr_ctrl_to_clk_length_match_mils=25.0` mil) to demonstrate the suite can genuinely detect a "
    "length-matching violation (thousands of mils out of a 25 mil budget). FOUND A THIRD REAL, "
    "REPRODUCIBLE GOTCHA attempting the fix on the shortest of these (N08984, a real 4-pin/multi-branch "
    "net): ripping up just one branch via `allegro_assign_net(ripup=True)` then recreating it with "
    "`allegro_create_trace` made `allegro_run_session` hang for minutes (vs the usual ~5-6s) -- "
    "REPRODUCED 2-FOR-2 on fresh board copies, with `DismissWatcher`'s own window enumeration finding "
    "zero dialog windows (just the normal main Allegro window still responding), ruling out the "
    "already-documented modal-dialog explanation. Root cause not isolated (candidate: recreating one "
    "branch of a net whose OTHER branches/pins are still attached at a shared junction may trigger an "
    "expensive connectivity/cline-merge recompute) -- flagged as a genuine, distinct limitation: "
    "`allegro_assign_net(ripup=True)` + `allegro_create_trace` is CONFIRMED reliable (~5-6s, every time) "
    "for a simple 2-pin/single-branch net (same mechanism used for the DRC-fix case above, and for the "
    "net below), but NOT yet confirmed reliable for a multi-branch net -- treat a multi-branch rip-up-"
    "and-refix as higher-risk until this is root-caused. SWITCHED to a simpler single-branch net pair "
    "(`N02684`=3100.0 mil, `N08580`=2400.0 mil, both `nBranches=1`) for the actual end-to-end "
    "demonstration: ripped up `N08580` via `allegro_assign_net(ripup=True)`, recreated it with a "
    "precisely-calculated rectangular meander sized to add exactly 700 mil (closing the 700 mil gap to "
    "`N02684`). FOUND A FOURTH thing worth recording, this one a real geometry-design mistake rather than "
    "a tool bug: a first attempt at the meander accidentally retraced part of its own path (two segments "
    "coincident on the same Y, one running back over part of the other's X range) -- `axlDBCreatePath` "
    "silently returned nil for this (0 segments created, `Missing Connections: 1`, same failure "
    "SIGNATURE as the layer-string bug above but a DIFFERENT cause -- self-overlapping path geometry, "
    "not a tool bug this time). A corrected, non-self-overlapping meander (verified point-by-point: no "
    "two segments share both an axis value AND an overlapping range) fixed it: `allegro_run_session` "
    "completed in the normal ~5-6s, `axlDBGetLength` independently confirmed the new real length as "
    "EXACTLY `3100.0` mil -- an exact match to `N02684`'s `3100.0` mil (0 mil residual, well inside the "
    "25 mil DDR4 budget) -- and `Missing Connections: 0`/`Connection Completion: 100.00%`/correct "
    "Nets(75)/Pins(251) counts confirmed full board integrity. 4 new minor spacing violations did appear "
    "against previously-unsurveyed neighbors in this new local area (same class of finding as the main "
    "DRC-fix case: picking a fully keepout-clean path by hand still requires surveying the specific "
    "local neighborhood, even in a seemingly simpler part of the board) -- the LENGTH objective itself "
    "was hit exactly. See `runs/routing_capability_investigation/t3_length_matching/` for the full "
    "before/after evidence of all four findings above.",
    "powerdc": "PDCVRM NET-PAIR INVESTIGATION: `powerdc_add_vrm` (`sigrity::add pdcVRM "
    "-auto -net {power,ground} -ckt {RefDes} -voltage {v}`) was suspected to be blocked by boards "
    "authored via `generate_multilayer_stackup` having no real copper on their PLANE layers (see the "
    "`allegro` note's COPPER SHAPE / PLANE POUR entry above for the fix built to test this). That "
    "hypothesis was TESTED LIVE AND NOT CONFIRMED. Build: an 8-layer board (incl. 2 PLANE layers) via "
    "`generate_multilayer_stackup`, a real copper pour via the new `allegro_create_copper_shape` on "
    "`L2_GND` bound to net `GND` (independently confirmed real, 3 ways -- see the `allegro` note), "
    "translated to `.spd` via the PowerSI BRD-bridge (the `.spd` literally contains `PatchSignal$L2_GND "
    "Shape = Plane$L2_GNDpkgshape Layer = Signal$L2_GND`), then `start_powerdc_session` + "
    "`powerdc_add_vrm(power_net=\"+15V\", ground_net=\"GND\", ref_des=\"U1\", voltage=15.0)` + "
    "`powerdc_run_session`. Result: `sigrity::add pdcVRM -auto -net +15V,GND -ckt U1 -voltage 15.0` "
    "still failed with the EXACT SAME error as before the copper fix: `The net pair '-net {power net "
    "name, ground net name}' is not specified.` (read from the real per-command `macro_<ts>_<pid>.log` "
    "PowerDC writes next to the attached `.spd` -- `list_job_files`/job.json show nothing useful here, "
    "same as the already-documented PowerDC fingerprint elsewhere in this suite). Ruled out, each with "
    "its own live run reproducing the IDENTICAL error text: (1) real copper present vs the original "
    "(no-copper) board -- no difference; (2) net name containing a '+' character (`+15V`) vs a plain "
    "alnum net (`SUPPLYBUS`) from the same board's real net list -- no difference; (3) `powerdc_set_"
    "simulation_mode` queued AFTER `start_powerdc_session`'s `-attach` (this suite's actual composed "
    "order) vs BEFORE it (matching Cadence's own shipped sample `share/SpeedXP/Samples/PowerDC/"
    "Electrical_Analysis/MB.tcl`'s order exactly) -- no difference; (4) `-auto` vs the doc's alternate "
    "short spelling `-a` -- no difference. The Tcl line this suite emits is byte-for-byte the same "
    "SHAPE as every real, Cadence-authored sample found on this install (`MB.tcl`, `Sample2_FEM_"
    "static_simulation.tcl`: `-net {PowerNets,GND} -ckt {...} -voltage {...}`) and matches the official "
    "doc format exactly (`doc/pdc_ug/c9_TCL_Create_by_Using_Existing_Components.html`: `-net "
    "{power_net_name, ground_net_name}`). LEADING HYPOTHESIS (not yet confirmed): every real Cadence "
    "sample's power side is literally the string `PowerNets` (never an actual "
    "board net name), and `IR_Package.pdcx` (this suite's own confirmed-live PowerDC IR-drop sample) "
    "contains literal `PowerNets`/`GroundNets` attribute values in its saved workspace XML -- suggesting "
    "`-net {X,Y}` in `-auto` mode resolves against PRE-DEFINED PowerDC Net Classes (set up via the GUI "
    "or Analysis Model Manager), not raw net-name strings, even though the doc's prose (\"power_net_"
    "name, ground_net_name\") reads as if literal net names are expected. A raw SPDIF-translated board "
    "with no AMM/Net-Class setup (exactly what this suite's `translate_*_to_spd`/PowerSI-bridge tools "
    "produce) may therefore never be able to satisfy `-auto -net` regardless of real net names or real "
    "copper -- `powerdc_add_vrm` should be treated as `built_untested`/unconfirmed until a Net-Class-"
    "defined design (or the real SKILL/Tcl call that defines one) is found and tried. Bottom line for "
    "future work: do NOT assume a `pdcVRM` net-pair failure means missing copper geometry -- it did "
    "not, here, even after independently proving the copper was real 3 separate ways. "
    "BOUNDED FOLLOW-UP: the leading hypothesis above (needs a pre-defined PowerDC Net "
    "Class before `-auto -net` can resolve) was tested, once, live. Found the real, documented "
    "defining command: `layoutworkbench_user/c15_tcl_re_Update_Net_AsPowerGndPair.html` -- `sigrity::"
    "update net AsPowerGndPair {net_name_1}{net_name_2}{!}` -- the Tcl equivalent of the Net Manager's "
    "GUI action (`c5_nets_tk_Setting_Nets_to_Power-Ground_Pair.html`: right-click nets, Classify > As "
    "Power-Ground Pair). No separate standalone 'define a PowerNets/GroundNets class' Tcl command "
    "exists anywhere in the vendored docs (searched `pdc_ug`, `layoutworkbench_user`'s full TCL "
    "chapter and JSON TOC) -- the GUI-documented `Classify > As PowerNets` / `As GroundNets` actions "
    "(`c5_nets_tk_Assigning_Net_to_Power_Net.html`, `...Ground_Net.html`) have NO Tcl-reference page at "
    "all, only `AsPowerGndPair`/`NotAsPowerGndPair` do. Reused the already-built, independently-"
    "verified copper-pour board (`runs/plane_pour_investigation/fd2.spd`, real `+15V`/`GND` nets, real "
    "copper on `L2_GND`) and inserted `sigrity::update net AsPowerGndPair {+15V} {GND} {!}` into the "
    "session immediately before the existing `powerdc_add_vrm` call, then reran the identical "
    "end-to-end flow. RESULT: REFUTED/INCONCLUSIVE, not confirmed. The command is real and ran (job "
    "state succeeded, rc 0), but failed on its OWN precondition before the `pdcVRM` line ever executed "
    "-- the real per-command macro log (`runs/plane_pour_investigation/macro_100226_163622_11600.log`) "
    "shows a NEW, different, specific error: `Cannot run the Tcl command 'sigrity::update net "
    "AsPowerGndPair' because the specified net '+15V' is not a power net. Ensure that the net is a "
    "power net and rerun the command.` -- i.e. `AsPowerGndPair` PAIRS two nets that must ALREADY be "
    "individually classified as power/ground first; it does not itself create that base "
    "classification. The only documented way to perform that base classification is the GUI-only "
    "Net Manager action (no Tcl command found for it anywhere in the vendored docs), or possibly "
    "`sigrity::spdif_option UseVoltageToClassifyNet {1}` set BEFORE BRD->SPD translation (an SPDIF "
    "translation-time option, found in `c15_tcl_re_Use_Voltage_Property_to_Classify_Power_Ground_"
    "Nets.html`, NOT exercised here -- untested, would require redoing the translation step, out of "
    "scope for this bounded investigation) combined with a per-net DC-voltage property that is itself GUI-only "
    "to set (`c5_nets_tk_Defining_DC_Voltage.html` -- no Tcl command documented). Per this "
    "investigation's explicit bound (one real attempt, no undocumented-name probing), stopping here: "
    "`powerdc_add_vrm`'s `-auto -net` failure mode remains open/inconclusive -- the Net-Class "
    "hypothesis is now better-specified (a two-stage classify-then-pair mechanism, both stages "
    "appearing to be GUI-only in every doc found so far) but not confirmed fixable via any Tcl path "
    "discovered. No new tool was added; `powerdc_add_vrm` stays `built_untested`.",
    "capture": "A real modal 'overwrite?' "
    "dialog needing a manual click, encountered while re-running one of this suite's own diagnostic "
    "scripts, led to root-causing a genuine, previously-misdiagnosed failure mode: a "
    "`.lck` file left behind by a prior batch job that was killed (rather than exiting "
    "cleanly) causes the NEXT launch against that same design path to block forever on "
    "an interactive 'already open/locked, override?' dialog with zero console output — "
    "this was previously misread as a generic hang or license-fetch delay. Fixed via "
    "`clear_stale_design_lock`, now called automatically in `start_capture_session` "
    "(and `allegro_run_session`) before launch — proven live for Allegro: a planted "
    "fake stale lock was auto-cleared and the job completed in 5.3s instead of hanging. "
    "Capture specifically, tested 3 clean runs in a row with this fix in place "
    "(fresh project-directory copy per run, to fully rule out lock confusion between "
    "runs): still genuinely non-deterministic — one run hung the full 90s wait with an "
    "empty log (had to be killed), runs 2 and 3 both reported 'succeeded' but in a "
    "suspicious 0.1s with a completely empty run.log, which is far too fast for a real "
    "open+script+close+exit cycle and matches this module's previously-documented "
    "'exits immediately with no output' failure mode rather than confirming real work "
    "happened. CONCLUSION: the stale-lock fix is real and directly proven for Allegro, "
    "and may explain some fraction of Capture's past non-determinism, but does NOT "
    "fully resolve it — something else about Capture's batch invocation remains broken "
    "or unconfirmed. Remains known_blocked; do not treat a fast 'succeeded' state alone "
    "as evidence the script's actual content (place parts, save, etc.) ran — check for "
    "real output/log content, not just the return code. Initially hit the same-looking 'Product Choices' dialog as allegro; "
    "after the user's fix, a bare `Capture.exe` launch (no arguments) now opens cleanly. "
    "However, the batch-script invocation (`-product=<name> script.tcl`) remains "
    "unreliable: repeated attempts inconsistently opened Capture's own default/tutorial "
    "project instead of running the given script, exited immediately with no output, or "
    "triggered a 'Capture Custom Launch' dialog -- which Cadence's own docs describe as "
    "a crash-recovery prompt ('displayed only after Capture fails at launching for the "
    "first time'), not a license chooser. Root cause not isolated (a Tcl syntax issue in "
    "the probe script, a version-specific CLI quirk, or something else) -- see "
    "capture_tools.py's module docstring. Against a real shipped sample project "
    "(tools/capture/samples/PCB-Layout/Fault-Detector/Fault-Detector.opj) with a minimal "
    "Open+Save+Close+Exit macro: the process launched (confirmed correct argv) but was "
    "still running with an empty log after 60s and had to be force-killed -- this rules "
    "out licensing as the cause; the batch-invocation unreliability is a "
    "separate, unresolved issue. With a full 5-minute wait "
    "(instead of 60s), to allow time for a possible one-time approval "
    "dialog to be clicked through manually, results are inconsistent across repeated "
    "attempts: one run completed cleanly in ~3.2s (open+save+close+exit, returncode 0), "
    "but the next fresh attempt hung with an empty log for the full 5 minutes "
    "and had to be killed. This confirms the 'inconsistent behavior' "
    "characterization precisely -- it is not a simple one-time dialog that, once "
    "accepted, permanently fixes every subsequent run (unlike allegro.exe's product-"
    "chooser dialog, which really was one-time). Treat capture_run_session as "
    "genuinely non-deterministic on this machine, not reliably blocked or reliably "
    "working. The root cause narrows to a specific "
    "machine-level defect: the hang reproduces with a *different*, simpler shipped "
    "sample project (FullAdder.opj, pure schematic, no PCB data) using ONLY the minimal "
    "Open+Close+Exit script (no placement at all) -- identical 0-byte log, no .lck file "
    "ever written into the project directory (i.e. the `Open <project>` step itself never "
    "completes, before any Part/Wire/Pin command has a chance to run), 100% CPU spin, and "
    "*zero* windows for the entire hang (checked live via EnumWindows, so it is not hidden "
    "behind a modal dialog of any kind, including the 'Capture Custom Launch' recovery "
    "dialog -- that specific dialog was separately traced to a genuine *prior*-session "
    "crash dump (ACCESS_VIOLATION in orPrmWebCompIE64.dll, see C:\\temp-builder\\Capture*/"
    "errorlog.xml), not the current hang itself; it is now auto-dismissed by "
    "capture_handle_custom_launch_dialog as a separate defensive guard for that distinct "
    "failure mode). Meanwhile `Capture.exe -version` alone returns cleanly in ~0.1s with no "
    "other Capture instance running -- so Capture.exe is not fully broken, but its project-"
    "opening code path (the first thing any real automation script does) hangs "
    "deterministically, with no CLI flag or documented workaround found in the local doc "
    "tree, and no reproducible fix available to this suite's Python wrapper layer; "
    "actually authoring schematics end-to-end on this machine would require a "
    "Cadence-level patch/reinstall or a working `syscap.exe` batch mode (see "
    "domains/cad/__init__.py's noted, not-yet-implemented lead).",
    "allegro_batch": "The multiplexer's own -help and '<program> -help' output is fine "
    "(genuinely headless, no dialog), but actually dispatching a sub-program through it "
    "is unreliable: `allegro_batch dbdoctor -check_only <real .brd>` failed immediately "
    "with 'ERROR: Cannot find program \"dbdoctor\"' (exit 2), while the identical "
    "operation via the standalone `dbdoctor.exe` succeeded. Tools call each underlying "
    "standalone exe directly (allegro_report, allegro_dbdoctor, ...) instead of routing "
    "through this multiplexer.",
    "allegro_report": "Confirmed genuinely headless, no dialog: `report.exe -v sum "
    "<real .brd sample> out.txt` produced a real, correct summary report end-to-end "
    "(package/pin/DRC/drill/connection statistics all present and accurate).",
    "celsius3d": "Confirmed live end-to-end against a real Cadence sample project on "
    "its FIRST run (share/PostInstallationCheck/celsius3d/case.3dth+case.tcl): "
    "`Celsius3D.exe -tcl case.tcl` exited 0, log showed 'Stress engine started and "
    "completed successfully!', and real numeric displacement/strain/stress results "
    "were written to case_Result_Summary.dat/.json in ~20-30s. IMPORTANT CAVEAT found "
    "via the multi-model eval harness (thermal_celsius3d_signoff task, both endpoints) "
    "and independently reproduced with a direct `timeout 20 Celsius3D.exe -tcl "
    "case.tcl` (exit 124): re-running against a project directory that already has a "
    "prior run's result folder (e.g. `<name>_SS_W/`) HANGS INDEFINITELY with an empty "
    "log — very likely a GUI overwrite-confirmation dialog, the same class of issue as "
    "Allegro/Capture's 'Product Choices' dialog. Always use a fresh copy of the project "
    "per run; never re-run in place. See celsius3d_tools.py's module docstring.",
    "celsiuscfd": "Confirmed live end-to-end against a real Cadence sample project on "
    "its FIRST run (share/PostInstallationCheck/celsiuscfd/pcb_pkg_sav.3dth+.tcl): "
    "`CelsiusCFD.exe -tcl pcb_pkg_sav.tcl` exited 0, log showed 'CelsiusECSolver is "
    "completed' and a real .cfd network file was generated. Not independently re-tested "
    "against an already-simulated project directory, but given Celsius3D's confirmed "
    "same-family hang in that scenario (see celsius3d's note), treat CelsiusCFD as "
    "likely subject to the same re-run-in-place risk until proven otherwise — use a "
    "fresh project copy per run.",
    "celsius2d": "Confirmed live against a real Cadence sample workspace "
    "(share/PostInstallationCheck/celsius2d/demo_sim.pdcx): `Celsius2D.exe -b -XIMSAVE "
    "-r demo_sim.pdcx` exited 0 with 'Simulation succeed' and full thermal+stress engine "
    "logs. A second sample (chip.pdcx) failed with a real domain-content error (an "
    "invalid referenced CFD file), not a launch/license/syntax failure — confirming "
    "errors surface as readable diagnostics rather than silently.",
    "allegro_dbdoctor": "Confirmed genuinely headless, no dialog: `dbdoctor.exe "
    "-check_only <real .brd sample>` ran a real orphan-record check end-to-end and "
    "reported its result ('1 warnings, 0 errors detected'). Note it exits non-zero "
    "(1) even for a clean check-only pass with only warnings — don't treat any non-zero "
    "return code from this tool as a hard failure without reading its output first.",
    "allegro_batch_drc": "Confirmed live against a real .brd sample on this machine: "
    "`batch_drc.exe -nographic <board>` exited 0 with 'Batch DRC checking done.'",
    "allegro_placement": "Confirmed live against a real .brd sample: `placement.exe "
    "<board> <out>` ran the genuine Allegro auto-place engine (real algorithm log with "
    "real weight/rotation parameters), but this specific sample board failed with "
    "'Error: No Package Keepin was found' — a board-authoring precondition (the board "
    "needs a defined placement keep-in area), not a wrapper or licensing problem. Retry "
    "against a board that already has a Package Keepin defined.",
    "allegro_ncroute": "Confirmed live against a real .brd sample: `ncroute.exe -o "
    "<out> <board>` exited 0 with 'Program completed. Done.'",
    "allegro_zrouter": "Automated via Allegro batch script (.scr) form replay — "
    "`run_allegro_zrouter` generates script commands to open the ZRouter dialog (`zrouter`), "
    "populate the Connections Control File (`FORM zrouter filename <path>`), optionally set "
    "grid spacing (`FORM zrouter grid <val>`), and execute fanout routing (`FORM zrouter execute`), "
    "saving the resulting board cleanly.",
    "allegro_ipc2581_out": "Confirmed live against a real .brd sample: `ipc2581_out.exe "
    "-o <out> <board>` exited 0 with 'a2ipc2581 complete.'",
    "allegro_ipc356_out": "Confirmed live against a real .brd sample: `ipc356_out.exe "
    "<board> <out>` exited 0 with 'Successfully generated file'.",
    "allegro_step_out": "Confirmed live against a real .brd sample: `step_out.exe -o "
    "<out> <board>` exited 0 with 'step_out complete.'",
    "ibischk6": "Confirmed live: `ibischk6.exe <real .ibs sample>` ran and correctly "
    "found real syntax errors/warnings in the sample model, exiting with its own "
    "'File Failed' verdict — that's the checker doing its job on a model with genuine "
    "issues, not a tool failure. ibischk3/4/5 share the same binary family/CLI shape "
    "but were not independently run.",
    "allegro_checkplus": "Attempted live against a real shipped example project "
    "(tools/checkplus_exp/concept/examples/physical, which has its own cp.dat) — failed "
    "both as a bare directory path and would also fail as a raw .brd: checkplus prints "
    "`**Error! [5038] Project File '<value>' does not exist` and a `**Warning! [5015] "
    "Missing '<cwd>/checkplus/cp.dat'` that ignores -proj's value for that specific "
    "check. This means -proj resolves through some CDS project-registration convention "
    "(not a plain filesystem path) that wasn't isolated from the doc tree. Not a license "
    "or launch problem — the tool runs and prints real, readable diagnostics — but the "
    "correct project_file value for it is still unconfirmed.",
    "allegro_extracta": "ROOT-CAUSED AND FIXED: "
    "`run_allegro_extracta`'s EXTRACTION_TEMPLATES used invented view-name/field-name "
    "keywords (\"NETS\", \"COMPONENTS\", \"PINS\", \"TESTPOINTS\", \"DRC\", "
    "\"COMP_LOCATION_X/Y\", \"COMP_ROTATION\", \"COMP_MIRRORED\", \"TESTPOINT_NAME\", "
    "\"DRC_ERROR_NAME\", ...) that real extracta.exe genuinely rejects outright for "
    "EVERY view_type with `ERROR(SPMHDX-10): Illegal view name.` -- this reproduces "
    "100% of the time (confirmed: 10 consecutive failed "
    "run_allegro_extracta+wait_for_job calls, 17 total "
    "wait_for_job 'state=failed, returncode=2' results for this tool overall) "
    "and is easy to misdiagnose, because the real "
    "error only appears in `extract.log`, which extracta.exe writes into its own "
    "process cwd -- i.e. the submitted JOB's own job_dir (per core.jobs' submit(), "
    "cwd=job_dir) -- not next to board_file/output_file where every attempt to read it "
    "looked (run.log's own text, 'Extract ended ... see extract.log for errors', gives "
    "no path, which is misleading here). Root cause confirmed by directly inspecting a "
    "job_dir's real extract.log by hand (not through any SKILL/tool layer). FIXED: "
    "EXTRACTION_TEMPLATES now uses the real, Cadence-documented view/field keywords "
    "copied directly from the shipped `share/pcb/text/views/*.txt` command files "
    "(bom_rep.txt/cmp_rep.txt -> COMPONENT, net_rep.txt -> LOGICAL_PIN, cpin_bv.txt -> "
    "COMPONENT_PIN, tstpoint.txt -> COMPOSITE_PAD, drc_rep.txt -> DRC_ERROR). "
    "LIVE-VERIFIED end-to-end against the real sample board (fd.brd) for all "
    "5 built-in view types (bom/nets/components/pins/drc): every one now returns "
    "state=succeeded, returncode=0, with real non-empty extracted data (e.g. drc view "
    "correctly listed real Package-to-Package and Line-to-Line spacing DRC violations "
    "on the sample board). If a caller needs a view this dict doesn't cover, prefer "
    "copying another real file from `share/pcb/text/views/` over guessing new "
    "view/field keywords -- extracta.exe's own error reporting for bad keywords is "
    "silent at the job-result level (run.log/returncode alone never show it); always "
    "check the job's own job_dir/extract.log, not a guessed path, when this tool fails.",
    "allegro_designextractor": "Attempted live: passing a raw .brd is confirmed rejected "
    "outright (immediate usage-banner re-print) — designextractor genuinely requires a "
    "populated .cpm/.sdax project file per its own -help text. For direct .brd database "
    "extraction, use `allegro_extracta` (extracta.exe) instead.",
    "allegro_extracta": "Allegro's native command-line database extraction engine. "
    "Extracts BOMs, nets, components, pins, test points, DRCs, and geometry from binary "
    ".brd files headlessly using predefined or custom extraction view control files.",
    "con2xml": "Real, installed executable (`C:\\Cadence\\SPB_22.1\\tools\\bin\\con2xml.exe`), "
    "translates a Concept-HDL `.con` netlist to XML. Fails at its own internal license "
    "check before argument parsing -- confirmed directly from the tool's own stderr "
    "(`No Product License selected... Translation cancelled.`), not merely an `lmstat` "
    "probe, against a real sample netlist "
    "(`share/pcb/translators/altium_proj_template/worklib/top/sch_1/top.con`). Exit "
    "code is 0 even on this failure -- do not treat a 0 return code as success for this "
    "tool. Whether this is the whole license server being unreachable or just this "
    "specific SPB Translators feature missing from an otherwise-working SPB 22.1 grant "
    "(the same install that serves `allegro`/`allegro_report` successfully) was not "
    "conclusively distinguished -- either way it is a genuine license/entitlement gate, "
    "not a bug in this MCP's integration, and no license-free workaround exists for "
    "Concept-HDL-to-XML conversion on this machine.",
    "cap2xml": "Real, installed executable (`C:\\Cadence\\SPB_22.1\\tools\\bin\\cap2xml.exe`), "
    "translates an OrCAD Capture `.opj` project to XML. Same license-gate failure as "
    "`con2xml`, confirmed against the real Fault-Detector Capture sample project "
    "(`tools/capture/samples/PCB-Layout/Fault-Detector/Fault-Detector.opj`): "
    "`No Product License selected... Translation cancelled.`, exit code 0. See `con2xml`'s "
    "note for the full license-gate caveat; no license-free workaround exists.",
    "dml2con": "Real, installed executable (`C:\\Cadence\\SPB_22.1\\tools\\bin\\dml2con.exe`), "
    "translates a DML (signal-integrity component model library) file to Concept-HDL. "
    "Same license-gate failure as `con2xml`, confirmed against a real sample "
    "(`share/pcb/signal/templates/hspice_bbox_template.dml`): `No Product License "
    "selected`, exit code 2. No license-free workaround exists; DML is a "
    "Cadence-proprietary format with no other reader on this machine.",
    "apd2con": "Real, installed executable (`C:\\Cadence\\SPB_22.1\\tools\\bin\\apd2con.exe`), "
    "bridges an Allegro Package Designer (APD) design to Concept-HDL. Same license-gate "
    "failure as `con2xml` (`No Product License selected`, exit code 2, tested with a "
    ".brd substituted for the missing APD format since the gate fires before format "
    "validation). Doubly blocked here: no `.apd` sample file exists anywhere in the "
    "install either, so even a working license would need an APD design obtained "
    "separately to exercise this tool.",
    "abcd": "Confirmed via `abcd.exe -help`'s full self-printed usage banner (real "
    "flag names/semantics). Cascades and de-embeds Touchstone S-parameter files; requires "
    "identical port counts, matching frequency points, 50-ohm reference impedance, and "
    "a space-free -filepath directory to avoid C++ solver crashes.",
    "bem2d3": "Confirmed via `bem2d3.exe -help`'s full self-printed usage banner (real "
    "flag names/semantics, tool's own banner still calls itself 'BEM2D2' internally), "
    "but not run against a real geometry input file on this machine.",
    "spif_batch": "`spif_batch.exe -o <board> <dsn>` (Allegro -> SPECCTRA .dsn export) is confirmed "
    "live: a real ~85KB .dsn was produced from a real sample board. For importing routed sessions "
    "back into Allegro, use `run_allegro_specctra_import`, which executes Allegro's native "
    "`specctra_in <session_file>` command via batch script replay to safely merge routes without "
    "database corruption errors -- see the `allegro` entry's specctra-import note for the real hang this "
    "had and its live-verified fix.",
    "specctra": "MAJOR CORRECTION to earlier research (see spif_batch's note): "
    "`specctra.exe <dsn> -nog -do <script>.do -quit` (Cadence's real, fully headless, "
    "SPECCTRA-based PCB autorouter) is confirmed live TWICE — against Cadence's own "
    "shipped tutorial design (100% connected, 0 conflicts) and against this suite's own "
    "real sample board (75 nets, 163 connections, 100% connected, 0 conflicts, real "
    ".ses session file written), both via the actual MCP tool wrapper "
    "(run_specctra_autoroute), not just raw CLI. Note it returns a nonzero exit code "
    "(confirmed: 4) even on a fully successful route — read final.sts/route.sts for "
    "real completion statistics rather than trusting the return code alone.",
    "psp_cmd": "MAJOR CORRECTION to earlier research, which classified PSpice as "
    "GUI-only after `pspice.exe`/`pspiceaa.exe` both hung on `-help`. `psp_cmd.exe` is "
    "a separate, dedicated batch-simulation executable in the same tools/bin, "
    "confirmed live: a bare invocation prints 'Missing circuit file argument' and "
    "exits immediately (no hang), and running it against a real shipped OrCAD PSpice "
    "sample genuinely loaded and attempted simulation, failing only on that sample's "
    "own portability issue (a missing .include file from the original authoring "
    "machine) with a specific, readable diagnostic.",
    "xcitepi": "Confirmed live end-to-end against a real Cadence sample "
    "(share/PostInstallationCheck/xcitepi/demo_decap.tcl + demo_decap.gds): "
    "`XcitePI.exe -b -tcl demo_decap.tcl` exited 0 and produced a real SPICE netlist "
    "(demo_decap.sp/_RLCK.sp) and IOME performance result "
    "(demo_decap_IOMESimResult.txt/.csv) via genuine `xpi_*` Tcl commands — a real full "
    "chip parasitic extraction ran to completion per its own engine log (15-25 min for "
    "a full 108 MB GDS, state stays `running` throughout -- do not cancel it as stuck). "
    "Default to this IOME path for any decap/chip-parasitic/IO-model extraction: reuse "
    "the proven macro order (`xpi_set_feature {IOME}` -> `xpi_set_tech_file` -> "
    "`xpi_open_file` -> `xpi_set_spice_output_path` -> `xpi_set_spice_option -pin -rc` "
    "-> `xpi_start` -> `xpi_save_iome_result`) verbatim rather than improvising. "
    "PME (bump-based decap extraction) is NOT feasible on this machine with any "
    "sample data shipped in the install: every XcitePI-relevant sample workspace was "
    "searched (share/XcitePI/Samples/XcitePI, share/Translators/Samples/Gds2Spd, "
    "share/PostInstallationCheck/xcitepi) and every one either has empty "
    "`<BumpPadPorts>` coordinates, has no `.dat` layout DB shipped to open it, or is "
    "the same die as demo_decap.gds. Root cause: the tech files that look bump-capable "
    "declare `.bump_pad gds_bumpcell <cellname>`, but that auto-bump mechanism only "
    "fires when the GDS is read with cell-tree parsing (`gdscelldisplay > 0`); the "
    "batch `xpi_open_file` path on this install reads the GDS as a flattened structure "
    "list instead, so the named bump cell is never matched and `xpi_start`'s validity "
    "check always fails with \"no BUMPS in Flip-Chip design\" regardless of which "
    "tech-file/subckt-file combination is tried. A second, real run against a different "
    "GDS/map pairing confirmed the identical failure, ruling out a staging mistake as "
    "the explanation. Do not attempt PME on this machine unless supplying a real "
    "flip-chip dataset with genuine bump placements (a GDS whose bump cells survive "
    "flattened parsing, a `.def` file for `xpi_add_bump -def`, or an existing `.xml` "
    "workspace with non-empty `<BumpPadPorts>` and its `.dat` DB present) -- none of "
    "these exist in the current install. SEPARATE BUG, applies to both features: "
    "`.include subckt_file_name` in a tech file is resolved relative to the job's own "
    "working directory, not the tech file's directory -- stage the subckt file into "
    "the job CWD or expect `(Error)Cannot find subckt file` and zero circuit "
    "placements. CRITICAL SEPARATE BUG: whenever `xpi_start`'s validity check fails "
    "(PME or otherwise), the process does not exit -- it enters an indefinite "
    "CPU-burning spin (confirmed ~25%-86% of one core, steady, for 65+ minutes across "
    "multiple real occurrences, zero further log/output growth) that only a manual "
    "kill ends. Treat any `xpi_start` validity-check failure as permanently hung from "
    "that point on: poll briefly to confirm the steady-CPU/zero-log signature, then "
    "kill the PID rather than waiting for it to exit on its own.",
    "optimizepi": "Confirmed live for OptimizePI.exe's own `-b -export_data` batch mode "
    "against a saved .opix workspace: using the complete real Cadence sample directory "
    "(share/PostInstallationCheck/optimizepi/), it fetched a license and reported "
    "'Simulation succeed', saving demo.spd. NOTE: this confirms the underlying "
    "OptimizePI.exe binary/license/batch-launch path works, but optimizepi_tools.py's "
    "own `sigrity::`-Tcl compose vocabulary (a different, session-based invocation "
    "style, `-b -tcl <script> -export_report`) was not independently re-run this same "
    "way — no Tcl-scripted sample shipped for OptimizePI to test that exact path "
    "against.",
    "xtractim": "Confirmed live end-to-end against a real Cadence sample "
    "(share/PostInstallationCheck/xtractim/Wirebond_EPA.ximx): `XtractIM.exe -b "
    "Wirebond_EPA.ximx` exited 0 and ran a genuine full-wave RLC extraction (real "
    "S600.2 solver engine log with frequency sweep, matrix size, and timing detail).",
    "dsn2spd": "Confirmed live against a real Cadence sample "
    "(share/Translators/Samples/Dsn2Spd/demo.dsn): `Dsn2Spd.exe -b demo.dsn demo.spd` "
    "exited 0, produced a real 723KB .spd file, and its own log itemized all 59 real "
    "components processed with no errors.",
    "t2b": "Attempted live against a real Cadence sample "
    "(share/SpeedXP/Samples/T2B/Example1/buffer.t2b + buffer.sp + hspice.mod): "
    "`T2B.exe -b buffer.t2b` genuinely launched, parsed the model, and dispatched real "
    "per-pin SPICE analysis jobs (rutout/rdtout/a00out/... .spi) — but every one aborted "
    "with 'Spice run (TYP) aborted.', ending in 'IBIS File Generation failed!'. T2B "
    "shells out to an external SPICE engine (HSpice, per the driver filenames and "
    "`hspice.mod` sample file) to characterize each buffer model — that engine is not "
    "installed/working on this machine. This is confirmed NOT a Cadence Sigrity license "
    "problem (T2B itself ran fine, no license-fetch failure) — it needs a working "
    "HSpice (or Cadence-integrated equivalent) install to actually produce output.",
    "spdsim": "Root cause narrowed: tried both the original `-b` flag AND the "
    "`-as`/`-spice -run` flags documented in `doc/psi_ug/"
    "ch10_tcl_re_Calling_SPDSIM_in_PowerSI_Commands.html` (a page titled 'Invoke "
    "Subprocesses', describing SPDSIM as something PowerSI's own Tcl `exec` command "
    "launches) — both flag styles produced the identical 'Skip license fetch' then "
    "'Failed to open the file' failure, against TWO different real samples (the legacy "
    "PostInstallationCheck ESD_testcase0.spd AND a modern PowerSI 3D-EM sample, "
    "diff_via.spd). The consistent 'Skip license fetch' message (never seen on any "
    "other confirmed-working tool in this suite) plus the doc page's own framing "
    "strongly suggests SPDSIM.exe is designed to run only as a genuine child process "
    "spawned by a live PowerSI Tcl session (inheriting some license/IPC context a "
    "freshly-launched standalone process doesn't have) — not really an independently "
    "callable batch tool despite living in tools/bin and accepting CLI flags. A real "
    "fix would mean driving it via `sigrity::do exec \"...spdsim.exe\" -as \"file.spd\" "
    "&` INSIDE a PowerSI Tcl session (powersi_tools.py) rather than as its own "
    "submit_job call — not yet implemented.",
    "abcd": "ATTEMPTED LIVE against three different real Touchstone file combinations "
    "(two 4-port .s4p files cascaded — segfaulted, exit 139; a single 2-port capacitor "
    ".s2p with -tsfile alone — silent no-op, no output, no error; two 2-port capacitor "
    ".s2p files cascaded via -lefttsfile/-righttsfile, both relative and absolute "
    "-filepath — also silent no-op). Demoted from built_untested to known_blocked: "
    "confirmed real via -help, but every real invocation tried either crashed or did "
    "nothing, with zero diagnostic output either way — root cause not isolated, "
    "possibly a frequency-grid/port-count compatibility requirement between the files "
    "that isn't obvious from the tool's own error reporting (which in this case is "
    "simply absent).",
    "allegro_checkplus": "`doc/checkplus/chap2.html`'s own title is "
    "'Setting Up Allegro Design Entry HDL Rules Checker' — checkplus is a rules "
    "checker for Design Entry HDL / Concept-HDL (a separate, legacy Cadence SCHEMATIC "
    "tool), not for Allegro PCB `.brd` physical layouts at all. Its `-proj` argument is "
    "a DE-HDL project reference, not anything resolvable from a `.brd` or a plain "
    "directory path — this fully explains the earlier 'Project File does not exist' "
    "result and means this tool is likely not applicable to a Capture-based (not "
    "DE-HDL-based) design flow at all, independent of the project-reference-format "
    "question.",
    "allegro_gbplot": "ROOT CAUSE FOUND AND FIXED: `doc/gcoms/gchap.html` "
    "documents the real syntax as `gbplot artwork_file_name [penplot_file_name] "
    "[-version]` — it takes an ALREADY-GENERATED Gerber `.art` artwork file, not a "
    "`.brd` directly (confirmed live: passing a `.brd`, as `run_allegro_gerber_plot` "
    "originally did, fails immediately with 'gbplot: Error opening parameter file.'). "
    "`run_allegro_gerber_plot` is now corrected to take an `artwork_file` argument (the "
    ".art output of `run_allegro_generate_artwork`, see `allegro_artwork` below) instead "
    "of a board file. Upgraded from known_blocked to built_untested — the fix is "
    "confirmed correct per the doc's own syntax, but gbplot itself (a legacy "
    "pen-plotter-format converter, not needed for standard Gerber/RS274X consumers) "
    "was not independently re-run against a real .art file.",
    "dxf2a": "CONFIRMED LIVE, and the answer to a real, previously-open gap: this suite "
    "had NO way to create a brand-new Allegro `.brd` from scratch before this. dxf2a's "
    "own `-help` banner documents its default (no `-g`) mode as \"new design, only\". "
    "Live-tested against Cadence's own shipped tutorial sample "
    "(doc/wb_tut/examples/Module_1/flag.dxf + flag_l.cnv): `dxf2a.exe -u MILS -a 2 "
    "flag_l.cnv flag.dxf out.brd` produced a real 203456-byte .brd. Independently "
    "verified (bypassing dxf2a/SKILL entirely): re-opened that exact file with "
    "report.exe (already confirmed_live elsewhere) and got a real summary — 2 routing "
    "layers, drawing extents matching the DXF outline's real geometry, 'DRC State: UP TO "
    "DATE'. Two confirmed quirks: (1) exits with returncode 1 even on this fully "
    "successful run (log ends 'dxf2a complete.') — same nonzero-on-success pattern as "
    "allegro_dbdoctor/artwork.exe/specctra elsewhere in this suite, don't trust job "
    "state alone; (2) flag syntax is confirmed SPACE-separated (`-u MILS`, `-a 2`) — the "
    "attached form (`-uMILS`, `-a2`) was live-tested and rejected outright with 'ERROR: "
    "Invalid program arguments.'. The sample flag_l.cnv also mapped a DXF layer to a "
    "class ('CONDUCTOR') a fresh empty design's default class table didn't recognize, "
    "producing repeated 'ERROR: Invalid class CONDUCTOR.' lines — dxf2a still completed "
    "and wrote a valid board regardless, but a caller should check the log for these "
    "before assuming every layer landed as mapped.",
    "ipc2581_in": "CONFIRMED LIVE — the import direction of the already-wrapped "
    "ipc2581_out. `-help` banner: \"Utility to import IPC2581 data to Allegro.\" Live-"
    "tested against the real shipped sample share/Translators/Samples/ipc2581/demo2.xml "
    "(3.4MB): produced a genuine 200KB .brd (basic import) and, with -x -g (import layer "
    "stackup + layer features), a fuller 1.58MB .brd -- both independently confirmed "
    "valid boards by re-reading with report.exe (real layer/DRC data). One real, "
    "readable warning surfaced (\"Layer stackup import failed.\") on the -x -g run -- not "
    "a crash, a genuine partial-import diagnostic to surface to the caller.",
    "idf_out": "CONFIRMED LIVE: `idf_out.exe <brd>` (bare form, all defaults) ran "
    "against a real sample board with zero preconditions and produced real "
    "<design_name>.bdf/.ldf output files (log: \"IDF out complete.\").",
    "idx_out": "CONFIRMED LIVE: `idx_out.exe <brd>` (bare form) ran against a real "
    "sample board with zero preconditions and produced a real 758KB .idx file (log: "
    "\"idx_out complete.\", genuine ProSTEP EDMD XML content confirmed by reading it).",
    "idf_in": "Real, fully self-documenting -help banner confirmed "
    "(`idf_in [-d <name_type>] <idf_file> [-o <output_design>] [-i <input_design>] "
    "[-p|-m|-f] [-a <accuracy>]`) -- explicitly supports creating a brand-new .brd from "
    "IDF mechanical data when -i is omitted (\"Default: <drawing_name>.brd\"), the same "
    "class of finding as dxf2a. Not live-tested: no real .emn/.bdf/.out (PTC/IDF/SDRC) "
    "sample file was found anywhere on this machine to test against.",
    "idx_in": "Real, fully self-documenting -help banner confirmed "
    "(`idx_in <idx_file> [-i <input_design>] [-o <output_design>]`), including a worked "
    "example. Not live-tested: no real .idx sample file was found on this machine.",
    "brd2dml": "CONFIRMED LIVE: `brd2dml.exe <brd>` (bare form) ran against a real "
    "sample board and produced a real 51KB .dml file with genuine "
    "`(Library (BoardModel (PinMap ...)))` DML content (verified by reading it).",
    "pdf_out": "CONFIRMED LIVE: `pdf_out.exe <brd>` (bare form) ran against a real "
    "sample board and produced a real 522KB PDF (verified real `%PDF-1.7` file-magic "
    "header), log ending \"pdf_out complete.\".",
    "copyproject": "CONFIRMED LIVE, independently verified twice (once via a live "
    "sweep of previously-unregistered executables, once by directly re-running it): "
    "`copyproject.exe -proj <source.cpm> -copytopath <dir> -newprojname <name> -newlib "
    "<lib> -newdesign <design>` against the real shipped sample project "
    "share/pcb/translators/altium_proj_template/altium_proj_template.cpm produced a "
    "complete, freshly-timestamped new project: a real CPM file (plain text, correct "
    "`design_name`/`design_library` fields), a full `worklib/<newdesign>/{sch_1,"
    "packaged,physical,cfg_package}` tree with real schematic pages and even a physical "
    "`.brd` placeholder, ending in \"SUCCESS(COPYPROJ-67): Copy Project Success.\" "
    "IMPORTANT: the created project file is named EXACTLY the `-newprojname` value with "
    "no `.cpm` extension appended automatically -- include the extension in "
    "`new_project_name` yourself if you want one. This is the strongest \"create a new "
    "schematic design from scratch\" finding in this whole pass -- it's flag-driven and "
    "fully headless (no GUI), unlike Capture.exe's/syscap.exe's unconfirmed batch "
    "reliability.",
    "xcon2project": "CONFIRMED LIVE: `xcon2project.exe -xcon <path.xcon> -root <name> "
    "-lib <libname> -refproj <ref.cpm> [-refcdslib <cds.lib>] [-output <dir>]` (note: "
    "the tool's own usage banner appends \"(-refproj must be specified)\" despite "
    "showing it in brackets -- treat it as required) run against a real populated "
    "project (share/pcb/translators/altium_proj_template/, which has a genuine non-"
    "template .cpm/cds.lib/.xcon) produced a real new project .cpm + cds.lib, log "
    "showing real \"Packaging design '<root>'\" status.",
    "generate_sim_variant": "CONFIRMED LIVE: genuinely creates a NEW derivative "
    "Allegro design for SI what-if analysis (over/undersizing trace widths and/or "
    "dielectric thicknesses from a master board) -- its own -help banner: \"Utility to "
    "generate a variant design from the provided master.\" `generate_sim_variant -c "
    "\"1.0\" -d \"1.0\" -o variant_out.brd <master.brd>` (percentage oversize on both "
    "clines and dielectrics) against a real sample board produced a real, distinct "
    "918KB new .brd -- independently confirmed valid (not a corrupt/stub copy) by "
    "re-reading it with report.exe (81 packages, 191 drills, 163 connections, matching "
    "the master's real content). NOTE from the tool's own -help: on-line DRC is "
    "deliberately disabled in the resulting variant design (elements may legitimately "
    "violate spacing against their oversized neighbors) -- don't re-enable/run DRC "
    "against a variant expecting a clean result.",
    "create_sym": "CONFIRMED LIVE, and a real correction to this suite's own earlier "
    "\"library authoring is GUI-only\" conclusion (that conclusion was about "
    "`symboleditor.exe`/`symbolcreator.exe`/`padstack_editor.exe`, which really are "
    "GUI-only -- `create_sym.exe` is a separate, distinct exe a prior audit pass "
    "missed). Its own -help: \"This is the command line version of File->Create "
    "Symbol.\" Live-tested against a real shipped footprint source "
    "(doc/lc_tut/tutorial_examples/Master_Library/Symbols/asp-134488-01.dra): "
    "`create_sym -p mysym.dra mysym.psm` produced a real 2.9MB .psm, log ending \"'mysym' "
    "saved to disk.\" -- independently re-verified with `dbdoctor.exe -check_only` "
    "against the result (\"0 warnings, 0 errors detected\").",
    "a2dxf": "CONFIRMED LIVE: run against this suite's own real routed sample board "
    "(tools/capture/samples/PCB-Layout/Fault-Detector/allegro/"
    "fault-detector_allegro_routed.brd) with a reused layer-conversion file, produced a "
    "genuine valid 6464-byte DXF (real SECTION/HEADER/$ACADVER/ENTITIES/EOF structure, "
    "confirmed by reading the file content directly), exit code 0, log ending 'a2dxf "
    "complete.'.",
    "allegro_artwork": "CONFIRMED LIVE end-to-end — this is the real fix "
    "for Gerber export, which `allegro_gbplot` alone could never provide (see its own "
    "note). `artwork.exe` has a full, real `-help` usage banner ('Generates Gerber "
    "films from Allegro designs'); `-l <board>` lists film records already defined. The "
    "missing piece was authoring those film records at all — Allegro's Artwork Control "
    "Form normally does this interactively, but the real documented SKILL equivalent, "
    "`axlFilmCreate` (now wrapped as `allegro_create_film` in allegro_geometry_tools.py), "
    "does it headlessly. Full pipeline confirmed live THREE times against fresh copies "
    "of the real sample board, including once through the exact unmodified production "
    "tool functions (allegro_create_film -> allegro_save_design -> allegro_run_session "
    "-> run_allegro_generate_artwork): defining ETCH/TOP and ETCH/BOTTOM films, saving, "
    "then running `artwork.exe <board>` produced real `TOP.art` (12225 bytes) and "
    "`BOTTOM.art` (6052 bytes) files in genuine RS274X Gerber format (verified file "
    "content: 'G04 File Format: Gerber RS274X', real layer/offset/rotation records). "
    "NOTE: artwork.exe exits 1 ('ARTWORK had warnings') even on this fully successful "
    "run — the warnings ('Can't open parameter file ... using default values', "
    "'Photoplot outline rectangle not found; using drawing extents') are the tool "
    "falling back to sane defaults, not errors — read photoplot.log/check for the "
    "actual .art files before treating a nonzero exit as failure.",
}


def get_tool_status(name: str) -> dict:
    status = TOOL_STATUS.get(name, "built_untested")
    return {
        "status": status,
        "description": STATUS_DESCRIPTIONS[status],
        "note": TOOL_STATUS_NOTES.get(name),
    }
